name: Deploy to vps

on:
  push:
    branches:
      - developer

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 200.234.232.44
          port: 2222
          username: miriam
          key: ${{ secrets.PRIVATE_KEY_DEV }}
          script: "cd /var/www/html/ecoCompostaje; git pull origin developer; php artisan route:clear; sudo service php8.3-fpm reload;npm run build;"
